services:
  database:
    image: postgres:17
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: oris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres