spring:
  application:
    name: spring-kr
  datasource:
    url: jdbc:postgresql://localhost:5432/oris
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    ru.kpfu.springkr: DEBUG

springdoc:
  swagger-ui:
    path: "/openapi"