spring:
  application:
    name: ORIS_Control_work

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/spring1
    username: postgres
    password: Uekz2005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081