spring.application.name=notes

spring.datasource.url=jdbc:postgresql://localhost:5432/kr_oris
spring.datasource.username=postgres
spring.datasource.password=19992006

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.web.pageable.default-page-size=8

server.port=8081