spring.application.name=oris_test1
server.port=8088

info.app.name=Test Work 1
info.app.version=1.0.0

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create